---
groups:
- name: branch-manager
  jobs:
  - branch-manager

resources:
- name: concourse-branch-manager
  type: git
  source:
    uri: https://github.com/simhachalamGunupudi/concourse-branch-mananger.git
    branch: master
    ignore_paths: [Gemfile, Gemfile.lock]

# This `git-branches` input resource determines which branches will be processed
- name: branch-manager-git-branches
  type: git
  source:
    # Set this to the uri of your repo for which you want to dynamically build arbitrary branches
    uri: https://github.com/simhachalamGunupudi/concourse-branch-mananger.git
    branch_regexp: ".*"
    max_branches: 20

# This repo containing your resource/job templates can be the same repo as
# the one in the git-branches resource above, but it doesn't have to be
- name: branch-manager-templates
  type: git
  source:
    # Set this to the uri of your repo containing your resource/job templates for building branches
    uri: https://github.com/simhachalamGunupudi/concourse-branch-mananger.git
    branch: master
#    paths: [examples/templates/*]

# This repo contains any non-secret non-credential config that needs to be
# passed into your generated pipeline via fly --load-vars-from options
- name: branch-manager-config
  type: git
  source:
    # Set this to the uri of your repo containing your non-secret non-credential config
    uri: https://github.com/simhachalamGunupudi/concourse-branch-mananger.git
    branch: master
#    paths: [examples/config/*]

# This repo contains any secret credential config that needs to be
# passed into your generated pipeline via fly --load-vars-from options
- name: branch-manager-credentials
  type: git
  source:
    # Set this to the uri of your repo containing your non-secret non-credential config
    uri: https://github.com/simhachalamGunupudi/concourse-branch-mananger.git
    branch: master
#    paths: [examples/credentials/*]

jobs:
- name: branch-manager
  serial: true
  plan:
  - get: concourse-branch-manager
    params: {depth: 20}
    trigger: true
  - get: git-branches
    resource: branch-manager-git-branches
    trigger: true
  - get: template-repo
    resource: branch-manager-templates
    params: {depth: 20}
    trigger: true
  - get: config-repo
    resource: branch-manager-config
    params: {depth: 20}
    trigger: true
  - get: credentials-repo
    resource: branch-manager-credentials
    params: {depth: 20}
    trigger: true
  - task: manage-branches
    file: concourse-branch-manager/tasks/manage-branches.yml



#    config:
#      platform: linux
#
#      image_resource:
#              type: docker-image
#              source: { repository: radial }
#              type: docker-image
#              source: { repository: busyboxplus }
#              type: docker-image
#              source: { repository: git }
#
#      inputs:
#      - name: my-repo-branch
#      - name: my-repo-common-resource
#
#      run:
#        path: my-repo-branch/examples/tasks/my-repo-branch-task-script
#



